### ISSUE TITLE
Can't pickle <function compute_loss_train at 0x7fbc72bf4dc0>

### ISSUE THREAD

**Issue by xiayuanj** [kiddyboots216/CommEfficient#15]
Hi, I'm having a new problem reproducing that code，could you please help me to fix it? Thanks a lot!
![image](https://github.com/kiddyboots216/CommEfficient/assets/53688836/599ba175-0975-41be-879a-a39a652ee0a2)
![image](https://github.com/kiddyboots216/CommEfficient/assets/53688836/ffb45e09-339b-4d98-aac9-c2f4c62c771c)

**Comment by kiddyboots216** [comment]
You actually can't run multiprocessing using the 'run' button in any IDE. The reason why is because that run button will wrap the script and call something other than __main__, whereas the multiprocessing needs to call something like __mp_main__. 

In order to run the script with multiprocessing you would have to run it from terminal.

**Comment by xiayuanj** [comment]
> You actually can't run multiprocessing using the 'run' button in any IDE. The reason why is because that run button will wrap the script and call something other than **main**, whereas the multiprocessing needs to call something like **mp_main**.
> 
> In order to run the script with multiprocessing you would have to run it from terminal.

Thanks a lot for your reply, it's very helpful for me.
